# Generated by Django 4.2.1 on 2023-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_spare_alter_bb_options_machine_advuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(error_messages={'min_length': 'Слишком мало символов'}, max_length=50, verbose_name='Товар'),
        ),
    ]
